puts "Seeding parties ..."

Party.create!([
  {name: 'BC Action Party', abbr: 'BCAP', color: '#DCDCDC'},
  {name: 'BC Cascadia Party', abbr: 'BCC', color: '#DCDCDC'},
  {name: 'BC Conservative Party', abbr: 'CP', color: '#0f5eaf'},
  {name: 'BC Excalibur Party', abbr: 'BCEX', color: '#DCDCDC'},
  {name: 'BC First', abbr: 'FP', color: '#DCDCDC'},
  {name: 'BC Green Party', abbr: 'GP', color: '#27bc6a'},
  {name: 'BC Liberal Party', abbr: 'LIB', color: '#c72636'},
  {name: 'BC Marijuana Party', abbr: 'BCM', color: '#DCDCDC'},
  {name: 'BC NDP', abbr: 'NDP', color: '#e87722'},
  {name: 'BC Party', abbr: 'BCP', color: '#DCDCDC'},
  {name: 'BC Refed', abbr: 'REFD', color: '#DCDCDC'},
  {name: 'BC Social Credit Party', abbr: 'SC', color: '#add8e6'},
  {name: 'BC Vision Party', abbr: 'BCV', color: '#DCDCDC'},
  {name: 'Christian Heritage Party of B.C.', abbr: 'CHP', color: '#cc6699'},
  {name: 'Communist Party of BC', abbr: 'COMM', color: '#ff6347'},
  {name: 'Helping Hand Party', abbr: 'HH', color: '#DCDCDC'},
  {name: 'Independent', abbr: 'IND', color: '#DCDCDC'},
  {name: 'Libertarian', abbr: 'LBN', color: '#f6c259'},
  {name: 'National Alliance Party', abbr: 'NAP', color: '#DCDCDC'},
  {name: 'No Affiliation', abbr: 'N/A', color: '#DCDCDC'},
  {name: 'Other', abbr: 'OTH', color: '#DCDCDC'},
  {name: 'Peoples Front', abbr: 'PF', color: '#DCDCDC'},
  {name: 'Platinum Party', abbr: 'PLAT', color: '#DCDCDC'},
  {name: 'Republican Party', abbr: 'RP', color: '#DCDCDC'},
  {name: 'The Advocational Party', abbr: 'AID', color: '#DCDCDC'},
  {name: 'The Sex Party', abbr: 'SEX', color: '#DCDCDC'},
  {name: 'The Vancouver Island Party', abbr: 'VIP', color: '#DCDCDC'},
  {name: 'Unparty: The Consensus-Building Party', abbr: 'UCBP', color: '#DCDCDC'},
  {name: 'Western Canada Concept Party', abbr: 'WCC', color: '#DCDCDC'},
  {name: 'Work Less Party', abbr: 'WLP', color: '#DCDCDC'},
  {name: 'Your Political Party of BC (YPP)', abbr: 'YPBC', color: '#222222'},
  {name: 'BC Moderate Democratic Movement', abbr: 'MDM', color: '#DCDCDC'},
  {name: 'BC Patriot Party', abbr: 'BCPA', color: '#DCDCDC'},
  {name: 'BC Unity Party', abbr: 'UPBC', color: '#DCDCDC'},
  {name: 'BC Youth Coalition', abbr: 'BCYC', color: '#DCDCDC'},
  {name: 'Bloc BC Party', abbr: 'BLOC', color: '#DCDCDC'},
  {name: 'Democratic Reform British Columbia', abbr: 'DRBC', color: '#DCDCDC'},
  {name: 'Emerged Democracy Party of BC', abbr: 'EDBC', color: '#DCDCDC'},
  {name: 'Freedom Party', abbr: 'FREE', color: '#DCDCDC'}
])