puts "Seeding parties ..."

Party.create!([
  {name: '4BC', abbr: '4BC', color: '#3dace0'},
  {name: 'BC Action Party', abbr: 'BCAP', color: '#fff797'},
  {name: 'BC Cascadia Party', abbr: 'BCC', color: '#03663d'},
  {name: 'BC Conservative Party', abbr: 'CP', color: '#0f5eaf'},
  {name: 'BC Citizens First Party', abbr: 'CFP', color: '#283878'},
  {name: 'BC Excalibur Party', abbr: 'BCEX', color: '#c3de5f'},
  {name: 'BC First', abbr: 'FP', color: '#30B1F3'},
  {name: 'BC Green Party', abbr: 'GP', color: '#27bc6a'},
  {name: 'BC Liberal Party', abbr: 'LIB', color: '#c72636'},
  {name: 'BC Marijuana Party', abbr: 'BCM', color: '#7d8c2f'},
  {name: 'BC NDP', abbr: 'NDP', color: '#e87722'},
  {name: 'BC Party', abbr: 'BCP', color: '#87cefa'},
  {name: 'BC Refed', abbr: 'REFD', color: '#FFFF99'},
  {name: 'BC Reform', abbr: 'RP', color: '#232777'},
  {name: 'BC Social Credit Party', abbr: 'SC', color: '#add8e6'},
  {name: 'BC Vision Party', abbr: 'BCV', color: '#b803e7'},
  {name: 'Christian Heritage Party of B.C.', abbr: 'CHP', color: '#cc6699'},
  {name: 'Communist Party of BC', abbr: 'COMM', color: '#ff6347'},
  {name: 'Helping Hand Party', abbr: 'HH', color: '#1bf804'},
  {name: 'Independent', abbr: 'IND', color: '#D0D0D0'},
  {name: 'Libertarian', abbr: 'LBN', color: '#f6c259'},
  {name: 'Land Air Water-The L.A.W.', abbr: 'LAW', color: '#000001'},
  {name: 'National Alliance Party', abbr: 'NAP', color: '#0a4958'},
  {name: 'No Affiliation', abbr: 'N/A', color: '#D0D0D1'},
  {name: 'Other', abbr: 'OTH', color: '#D0D1D0'},
  {name: 'Peoples Front', abbr: 'PF', color: '#fe5519'},
  {name: 'Platinum Party', abbr: 'PLAT', color: '#f0f0f0'},
  {name: 'Republican Party', abbr: 'NRP', color: '#0033FF'},
  {name: 'The Advocational Party', abbr: 'AID', color: '#1c4f03'},
  {name: 'The Sex Party', abbr: 'SEX', color: '#ff69b4'},
  {name: 'The Vancouver Island Party', abbr: 'VIP', color: '#7b37a6'},
  {name: 'Unparty: The Consensus-Building Party', abbr: 'UCBP', color: '#079708'},
  {name: 'Western Canada Concept Party', abbr: 'WCC', color: '#9b2e2d'},
  {name: 'Work Less Party', abbr: 'WLP', color: '#FF3366'},
  {name: 'Your Political Party of BC (YPP)', abbr: 'YPBC', color: '#000000'},
  {name: 'BC Moderate Democratic Movement', abbr: 'MDM', color: '#FFFFCC'},
  {name: 'BC Patriot Party', abbr: 'BCPA', color: '#da70d6'},
  {name: 'BC Unity Party', abbr: 'UPBC', color: '#48d1cc'},
  {name: 'BC Youth Coalition', abbr: 'BCYC', color: '#bc8f8f'},
  {name: 'Bloc BC Party', abbr: 'BLOC', color: '#91d87e'},
  {name: 'Democratic Reform British Columbia', abbr: 'DRBC', color: '#db7093'},
  {name: 'Emerged Democracy Party of BC', abbr: 'EDBC', color: '#000077'},
  {name: 'Freedom Party', abbr: 'FREE', color: '#fe2441'},
  {name: 'All Nations Party', abbr: 'ANP', color: '#03efc1'},
  {name: 'Western Reform', abbr: 'WR', color: '#9c825f'},
  {name: 'BC Citizens Alliance Now', abbr: 'BCCA', color: '#14fdee'},
  {name: 'Council of British Columbians', abbr: 'COBC', color: '#cde4bd'},
  {name: 'Party of Citizens Who Have Decided to Think for Themselves and Be Their Own Politicians', abbr: 'POC', color: '#986cdb'},
  {name: 'Citizens Commonwealth Federation', abbr: 'CFED', color: '#2f6cc6'},
  {name: 'Central', abbr: 'CENT', color: '#b2abfb'},
  {name: 'Progressive Democratic Alliance', abbr: 'PDA', color: '#AA99CC'},
  {name: 'Common Sense, Community, Family', abbr: 'CCF', color: '#705b97'},
  {name: 'Natural Law', abbr: 'NLP', color: '#2691d5'},
  {name: 'Family Coalition', abbr: 'FCP', color: '#fdb342'},
  {name: 'Wexit BC', abbr: 'WX', color: '#FF7F50'},
  {name: 'Rural BC Party', abbr: 'RU', color: '#B8860B'}
])